baseURL = "https://blank.blue/"
title = "Blank"
theme = ["blank"]
defaultContentLanguage = "fr"
uglyURLs = false
buildFuture = true
enableGitInfo = true

enableInlineShortcodes = true
relativeURLs = true
canonifyURLs = true
removePathAccents = true

[params]
 subtitle = "Lieu en d·efl·exion"
 description = "blabla"
 keywords = "blablamotclef"
 repo = "https://github.com/Mmellet/Blank"
 source = "Blank.blue"

[outputFormats.print]
isPlainText = true
mediaType = 'text/plain'
path = 'print' # triggers #13829
permalinkable = true
ugly = true

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[permalinks]
  pages = "/:filename"
  meditions = "/meditions/:title"  
  petites = "/petites/:title"
  carnet = "/carnet/:title"
  creations = "/creations/:title"
  inferences = "/inferences/:title"
  outopies = "/outopies/:title"

[menu]
  [[menu.main]]
    name = "Méditions"
    pre = "meditions"
    url = "/meditions/"
  [[menu.main]]
    name = "Petites"
    pre = "petites"
    url = "/petites/"
  [[menu.main]]
    name = "Carnet"
    pre = "carnet"
    url = "/carnet/"
  [[menu.main]]
    name = "Créations"
    pre = "creations"
    url = "/creations/"
  [[menu.main]]
    name = "Inférences"
    pre = "inferences"
    url = "/inferences/"
  [[menu.main]]
    name = "Outopies"
    pre = "outopies"
    url = "/outopies/"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2
    ordered = false
  [markup.goldmark]
    typographer = true
    [markup.goldmark.renderer]
     footnoteReturnLinkContents = "&uarr;"
      unsafe = true
  [markup.goldmark.extensions.figcap]
      figcap = true
  [markup.goldmark.parser]
    attribute = true

rssLimit = 200
copyright = "2021 Margot Mellet CC BY-NC-SA"
languageCode = "fr-fr"

[author]
  name = "Margot Mellet"
  firstname = "Margot"
  lastname = "Mellet"
	email = "margot.mellet@usherbrooke.ca"
  orcid = "à remplir"

